[package]
name = "advent"
version = "0.1.0"
authors = ["Reiner Herrmann <reiner@reiner-h.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
